### ISSUE TITLE
terraform-provider-circleci: exec format error

### ISSUE THREAD

**Issue by prawadhwani** [thiagoalessio/terraform-provider-circleci#2]
* Built it using `go get -u github.com/thiagoalessio/terraform-provider-circleci`
* Copied the binary from `~/go/bin/terraform-provider-circleci` to my terraform deployment folder.
* Ran using docker `docker run -i -t -v $(pwd):/app/ -w /app/ hashicorp/terraform:light plan`
* Got 
```
Error: Error asking for user input: 1 error(s) occurred:

* provider.circleci: fork/exec /app/terraform-provider-circleci: exec format error
```

**Comment by sysradium** [comment]
Because `go get` compiled it with `GOOS=darwin`, you need `GOOS=linux`.
Just do something like:
```
cd $GOPATH/src/github.com/thiagoalessio/terraform-provider-circleci
GOOS=linux go build . 
docker run -i -t -v $(pwd):/app/ -w /app/ hashicorp/terraform:light plan
```
