### ISSUE TITLE
Release for Darwin ARM64 (M1 Mac)

### ISSUE THREAD

**Issue by tomtaylor** [thiagoalessio/terraform-provider-circleci#25]
It would be great to cut a release of this for M1 Macs, using the Darwin ARM64 architecture. I believe goreleaser already supports this, and the config already includes arm64 architectures. I think just running the `release` workflow again should do the trick. You might need to bump the patch version to kick Github Actions into life!

**Comment by TomTucka** [comment]
Hey @tomtaylor! 

Sorry for the very late response! v0.5.0 should contain the the Darwin ARM64 binary

**Comment by tomtaylor** [comment]
Thanks!
